server:
  port: 9090

spring:
  application:
    name: action-service


  datasource:
    url: jdbc:mysql://localhost:3306/cms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

token-reset:
  hours: 9
  mins: 0
