spring:
  application:
    name: Feign Client App


  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9091

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


jwt:
  secret-key: "BmoD/XUVKSxA5z2JNhrdiDl/1tF6N5QpLWPgVmO0RAE="
  issuer: "my-bank"
  expiry: 600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/